name: AITranslator
version: 1.0
main: org.pytenix.TranslatorPlugin
api-version: 1.20 # Oder deine Zielversion
author: PytenixOG
description: Übersetzt Chat-Pakete asynchron via OpenAI
folia-supported: true
depend: [ packetevents ]
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
commands:
  testmsg:
    description: Sendet eine komplexe Testnachricht mit Hover und Klick
    usage: /testmsg