syntax = "proto3";

package org.omni.proto;

option java_package = "org.omni.proto.generated";
option java_outer_classname = "Protobuf";

// ==========================================
// CONFIGURATION & ENUMS
// ==========================================

enum ConsentType {
  UNKNOWN = 0;
  EXPLICIT = 1;
  AUTO = 2;
  DECLINED = 3;
}

enum ConsentMode {
  CONSENT_UNKNOWN = 0;
  CONSENT_STRICT = 1;
  CONSENT_EXTERNAL = 2;
  CONSENT_AUTO_OPT = 3;
}

enum Module {
  MODULE_UNKNOWN = 0;
  MODULE_LIVE_CHAT = 1;
  MODULE_GUI = 2;
  MODULE_HOLOGRAM = 3;
  MODULE_PLUGIN_CHAT = 4;
  MODULE_SIGNS = 5;
  MODULE_MOTD = 6;
}

enum CacheInvalidationType {
  CACHE_UNKNOWN = 0;
  CACHE_PROFILE = 1;
  CACHE_TRANSLATION = 2;
}

message ServerConfiguration {
  string license_key = 1;
  string default_language = 2;
  ConsentMode consentMode = 3;
  repeated Module active_modules = 4; // Liste aller Module, die auf 'true' stehen
  repeated string words = 5;
}

message DataExportRequest
{
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;

  bytes analytics_id = 3;
}

message DataExportResult
{
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;

  string dataLink = 3;
}


message ConfigRequestPacket {
  int64 timestamp = 1;
}

// ==========================================
// TELEMETRY & ANALYTICS (DSGVO konform)
// ==========================================

message HeartbeatPacket {
  int64 timestamp = 1;

  fixed64 request_id_most_sig = 2;
  fixed64 request_id_least_sig = 3;

  int32 total_online = 4;

  int32 translation_unknown_count = 5;
  int32 translation_explicit_count = 6;
  int32 translation_auto_count = 7;
  int32 translation_declined_count = 8;

  int32 analytics_unknown_count = 9;
  int32 analytics_explicit_count = 10;
  int32 analytics_auto_count = 11;
  int32 analytics_declined_count = 12;

  map<string, int32> lang_distribution = 13;
}

message TrackPlayerPacket {
  int64 timestamp = 1;

  fixed64 request_id_most_sig = 2;
  fixed64 request_id_least_sig = 3;

  bytes analytics_id = 4;
  int32 playtime_seconds = 5;
  bool is_translated = 6;
  string language = 7;
}

// ==========================================
// PLAYER PROFILES & CONSENT
// ==========================================

message ConsentRefreshRequest {
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;

  fixed64 user_id_most_sig = 3;
  fixed64 user_id_least_sig = 4;

  ConsentType translation_consent_type = 5;
  ConsentType analytics_consent_type = 6;
}

message ProfilePacket {
  fixed64 request_id_most_sig = 3;
  fixed64 request_id_least_sig = 4;

  bytes analytics_id = 5;

  ConsentType translation_consent_type = 6;
  ConsentType analytics_consent_type = 7;
}

message ProfileExternRequest {
  string license = 1;
  fixed64 request_id_most_sig = 2;
  fixed64 request_id_least_sig = 3;
  bytes analytics_id = 4;
}

message ProfileExternUpdate {
  ProfilePacket profilePacket = 1;
}

// ==========================================
// TRANSLATION & GEO-IP
// ==========================================

message GeoRequestPacket {
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;
  string ip_address = 3;
}

message GeoResultPacket {
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;
  string language = 3;
}

message TranslationRequest {
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;

  string text = 3;
  string target_lang = 4;
  Module module = 5;
}

message TranslationResult {
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;
  string result = 3;
}

// ==========================================
// CACHING
// ==========================================

message CacheInvalidationRequest {
  fixed64 request_id_most_sig = 1;
  fixed64 request_id_least_sig = 2;
  oneof payload {
    ProfileInvalidation profile_invalidation = 3;
    TranslationInvalidation translation_invalidation = 4;
  }
}

message ProfileInvalidation {
  bytes analyticId = 1;
}

message TranslationInvalidation {
  string text = 1;
  string language = 2;
  Module module = 3;
}

// ==========================================
// WRAPPER
// ==========================================

message PacketWrapper {
  oneof payload {
    ServerConfiguration config = 1;
    ConfigRequestPacket config_request = 2;
    GeoRequestPacket geo_request = 3;
    GeoResultPacket geo_result = 4;
    TranslationRequest translation_request = 5;
    TranslationResult translation_result = 6;
    ProfilePacket profile_packet = 7;
    ConsentRefreshRequest consent_refresh_request = 8;
    HeartbeatPacket heart_beat_packet = 9;
    TrackPlayerPacket track_player_packet = 10;
    ProfileExternRequest profile_extern_request = 11;
    ProfileExternUpdate profile_extern_update = 12;
    CacheInvalidationRequest cache_invalidation_request = 13;
    DataExportRequest data_export_request = 14;
    DataExportResult data_export_result = 15;
  }
}